### ISSUE TITLE
Issue when restoring from cache on Runners

### ISSUE THREAD

**Issue by valpinkman** [moonrepo/setup-proto#2]
Hello there, 

I've tried to use this action to setup proto in CI. It mostly works, but it seems there is an issue restoring from cache on.

Here is a screenshot of the logs
Windows:
<img width="1060" alt="CleanShot 2023-05-30 at 14 41 48@2x" src="https://github.com/moonrepo/setup-proto/assets/671786/b34c2206-abcf-47b2-b6e7-5ea3d81542c4">
Also on Windows:
<img width="1030" alt="CleanShot 2023-05-30 at 14 50 28@2x" src="https://github.com/moonrepo/setup-proto/assets/671786/a4ce596b-4736-4480-b06f-483ff7aece23">

macOS:
<img width="1075" alt="CleanShot 2023-05-30 at 14 47 40@2x" src="https://github.com/moonrepo/setup-proto/assets/671786/093c2ac7-ce27-4de5-be5d-5ece0c5ca46d">

**Comment by milesj** [comment]
Ok this seems to be a few issues:

This should fix the "already exists" error: https://github.com/moonrepo/setup-proto/commit/1fb170e9812fabc8357622ce14b1ec512df95933

And proto v0.10 reworks how windows shims work: https://github.com/moonrepo/proto/pull/115
